server:
  port: 8080

# DataSource Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nomad
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  main:
    allow-circular-references: true

  # JPA Configuration
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Spring Security
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000



  # OAUTH2
  # spring.security.oauth2.resourceserver.jwt.issuer-uri: ${JWT_ISSUER_URI}

  # HikariCP Configuration
  datasource:
    hikari:
      maximum-pool-size: 30
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
